services:
  dashboard:
    container_name: homainer_dashboard
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
    - ./src/config:/homainer/config
    ports:
      - 7777:7777
    networks:
      - main
networks:
  main:
    name: main
    driver: bridge